bundler_args: ""
script: "bundle exec rake spec"
sudo: false
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
branches:
  only: master
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
