bundler_args: ""
script: "bundle exec rake spec"
rvm:
  - ree
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
bundler_args: --no-deployment
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails23.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails40.gemfile
